# Generated by Django 4.0.4 on 2022-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ratings', models.IntegerField()),
                ('cast', models.CharField(blank=True, max_length=255)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
    ]
